arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
# console:
# flutter pub add flutter_localizations:"{sdk: flutter}" intl:any
#flutter gen-l10n
#  flutter run
#  flutter pub get
#####dont forget to add generate below the last flutter title
#flutter:
#
#  # The following line ensures that the Material Icons font is
#  # included with your application, so that you can use the icons in
#  # the material Icons class.
#  uses-material-design: true
#  generate: true   <<<<<=======